apiVersion: apps/v1
#apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: solo
  name: solo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: solo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: solo
    spec:
      containers:
      - image: hbr.hf.cn/test/solo:v1.3
        name: solo
        env:
        - name: JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: JDBC_USERNAME
        - name: JDBC.PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: JDBC_PASSWORD
        - name: JDBC_DRIVER
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: JDBC_DRIVER
        - name: RUNTIME_DB
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: RUNTIME_DB
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: JDBC_URL
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "800m"
status: {}
